### ISSUE TITLE
Variable Naming, exclude some starting charachter

### ISSUE THREAD

**Issue by f4n0** [JalmarazMartn/JAMALVariablenaming#1]
Hi,
I've just found out about your extension and it looks great!
Just one thing about the variable naming:
We use prefixed variables but with a twist:
Our AS prefix is "EOS" but we also add the app number after it, like so "EOS004".
Now, if I exclude the just EOS, it will rename the variable as `"004MyName"`, with the double quotes, and honestly, I don't really like it.

Could it be possible to trim the starting characters that are not allowed for naming? 

Before yours, I used this extension https://github.com/RasmusTidselbak/al-var-helper but it is not anymore supported, I even created a pull request to avoid my issue, but without any response.

**Comment by JalmarazMartn** [comment]
Thank you for you feedback.

I will solve your request soon in a few days, because I am finishing my next extension https://marketplace.visualstudio.com/items?itemName=JessAlmarazMartin.customdiagnostics this is the link if you want to try it.

I am thinking two ways to do this:

- You can set a prefix (param **AppPrefix**) for workspace in my extension (in fact in all the extensions), so you can set it for every extension, in one workspace EOS004, in another EOS005 and so on. You can do this yourself, without any help.
- Other option: I can modify my extension to set a regular expression in this parameter: AppPrefix :"EOS\d{3}". My favorite one.

Best regards, comments are welcome.

**Comment by f4n0** [comment]
In my PR of the other extension, I've used a regex like this one:

 exact = exact.replace(/^(\d|\.)+/gm, "");

Hope it helps!

Also the other option looks great!

**Comment by JalmarazMartn** [comment]
> In my PR of the other extension, I've used a regex like this one:
> 
> exact = exact.replace(/^(\d|.)+/gm, "");
> 
> Hope it helps!
> 
> Also the other option looks great!

With new extension release you can set the prefix as a regular expression to exclude this way the digts:   AppPrefix: "EOS[\d]*", and the prefix EOS and its digits will be remove from variable name, this way:

AreaSetup  :Record "EOS004 Area Setup".

Hope this can solve.
